import type { Metadata } from "next";
import { ClashDisplay, IndieFlower } from "@/utils/customFonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${ClashDisplay.variable} ${IndieFlower.variable}`}>
        {children}
      </body>
    </html>
  );
}
